import type { Metadata } from "next";
import "./styles/reset/reset.scss";
import Menu from "./components/menu";
import RocketLoader from "./share/loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Menu />
        <RocketLoader />
        {children}
      </body>
    </html>
  );
}
